name: Deploy Client

on:
  push:
    branches:
      - master
    paths:
      - client/src/**
      - client/public/**

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd client
          npm install
          npm run build
        env:
          REACT_APP_URL: ${{ secrets.URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: client/build
