name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - server/src/**

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Heroku Docker
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          appdir: "server"
          usedocker: true

          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
